#!/usr/bin/env python

import sys

def usage():
    print("usage: " + sys.argv[0] + " number");

def i2c_conv(num):
    num >>= 1
    return num


if __name__ == '__main__':
    if len(sys.argv) != 2:
        usage()
        sys.exit(1)

    num = int(sys.argv[1], 16)
    num = i2c_conv(num)
    print(hex(num))
