#!/usr/bin/env bash

set -o errexit # error terminate script
set -o nounset # use no unset variables

function usage ()
{
cat <<ENDUSAGE

usage:
"$0 <netdev>"
"$0 eth2"
ENDUSAGE
exit 1
}

if [[ $# -ne 1 ]] ; then
   echo "No device given"
   usage
fi

device=$1

if [[ x"${device}" == "x" ]]; then
    echo "Usage: $0 net-device";
    exit 1;
fi

if [[ $(mount | grep sysfs 2>&1 > /dev/null) ]]; then
    echo "Sysfs not mounted"
    exit 1
fi


if [[ ! -d /sys/class/net/${device} ]]; then
    echo "No sysfs entry for net-device ${device}";
    echo "Are you shure it exists?"
    exit 1
fi

for err in /sys/class/net/${device}/statistics/*err*; do
    printf "%s %-20s" ${device} $(basename "${err}")
    cat "${err}"
done
