#!/bin/sh
set -e
set -o nounset

DISTRO="tumbleweed"

usage()
{
	prog="$(basename $0)"
	echo "$prog <directory>"
}

if [ $# -lt 1 ]; then
	usage
	exit 1
fi

DIR=$1

if [ $# -gt 1 ]; then
	DISTRO="$2"
fi


case "${DISTRO}" in
	tumbleweed)
		URL=http://download.opensuse.org/tumbleweed/repo/oss
		;;
	13.1)
		URL=http://download.opensuse.org/distribution/13.1/repo/oss
		;;
	13.2)
		URL=http://download.opensuse.org/distribution/13.2/repo/oss
		;;
	leap42.1)
		URL=http://download.opensuse.org/distribution/leap/42.1/repo/oss
		;;
	*)
		echo "Unknown distribution ${DISTRO}"
		exit 1
		;;
esac

zypper --root "${DIR}" ar "${URL}" repo-oss
zypper --non-interactive --no-gpg-checks --root "${DIR}" install rpm zypper

