#!/usr/bin/env bash

set -e

BASE="origin/master"
NPROCS=$(grep -c ^processor /proc/cpuinfo)
BRANCH=$(git branch -l | grep "^*" | cut -d ' ' -f 2)

die()
{
    local commit=$1
    echo "Commit ${commit} breaks the build";
    exit 1;
};

if [ $# -eq 1 ]; then
	BASE="$1"
fi

for COMMIT in $(git log --reverse --format=format:%H ${BASE}..HEAD); do
    git checkout ${COMMIT};
    make -j${NPROCS} 1>/dev/null || die ${COMMIT}
done

git checkout ${BRANCH}
echo "Branch ${BRANCH} is fully bisecable"
